name: Backend Tests

on:
  push:
    branches: [ main, dev, Owen ]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      # Install dependencies
      - name: Install Python dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # Run pytest
      - name: Run pytest
        working-directory: backend
        env:
          PYTHONPATH: ${{ github.workspace }}/backend
          FLASK_ENV: testing
          # SQLite fallback is already handled in create_app,
          # but you can force in-memory DB explicitly if you like:
          SQLALCHEMY_DATABASE_URI: sqlite:///:memory:
        run: pytest --maxfail=3 --disable-warnings -q --cov=app --cov-report=term-missing
