name: Run Test Cases

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'   # adjust if your project uses a different version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest

      - name: Run pytest
        working-directory: backend
        run: pytest --maxfail=3 --disable-warnings -q
